[build]
  command = "ng build --configuration production"
  publish = "dist/portfolio" # Adjust based on your Angular project name

[context.production]
  environment = { NODE_VERSION = "18" } # Specify Node.js version if needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200